# Lets you enable / disable certain features and modify them.
[features]
	# (Default = false) Makes villagers tick less often if they are stuck in a 1x1 space.
	lobotomize_villagers = true
	# (Default = 0.5) Decides the radius in blocks that items / xp will merge at.
	item_merge_radius = 0.75
	xp_merge_radius = 1.0

# Allows you to toggle specific optimizations that don't have full vanilla parity.
# These settings will only take effect after server restarts.
[optimizations]
	# (Default = false) Can significantly reduce time spent on mobspawning, but isn't as accurate as vanilla on biome borders.
	# This may cause mobs from another biome to spawn a few blocks across a biome border (this does not affect structure spawning!).
	fast_biome_lookups = true
